version: "3.9"

services:
  api:
    build:
      context: ./nest-comic
      dockerfile: ./nest-comic/Dockerfile

  client:
    build:
      context: ./next-comic
      dockerfile: ./next-comic/Dockerfile

  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
